version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps):"
  - package-ecosystem: terraform
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps):"
